from algorithms.fcfs import FCFS
from algorithms.nonpreemptive_SFJ import NonPreemptiveSFJ
from algorithms.preemptive_SFJ import PreemptiveSFJ
from algorithms.nonpreemptive_priority import NonPreemptivePriority
from algorithms.preemptive_priority import PreemptivePriority
from algorithms.rr import RR
